server:
  port: 9005

spring:
  application:
    name: mail-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d7c3e4b3-1bc9-47a3-9a51-9adf6b71895b
        group: dev



